### ISSUE TITLE
data.txt not generated

### ISSUE THREAD

**Issue by BeNeDeLuX** [evilbunny2008/weeWxWeatherApp#1]
There is no data.txt generated for me. Here is the error from syslog:

```
> Apr  2 21:58:02 weewx weewx[13633]: engine: Starting up weewx version 3.8.0
> Apr  2 21:58:02 weewx weewx[13633]: engine: Starting main packet loop.
> Apr  2 21:58:11 weewx weewx[13633]: interceptor: MainThread: skipping rain measurement of 0.01: no last rain
> Apr  2 22:00:20 weewx weewx[13633]: manager: Added record 2018-04-02 22:00:00 CEST (1522699200) to database 'weewx.sdb'
> Apr  2 22:00:20 weewx weewx[13633]: manager: Added record 2018-04-02 22:00:00 CEST (1522699200) to daily summary in 'weewx.sdb'
> Apr  2 22:00:20 weewx weewx[13633]: forecast: ZambrettiThread: Zambretti: generated 1 forecast record
> Apr  2 22:00:20 weewx weewx[13633]: restx: MQTT: Published record 2018-04-02 22:00:00 CEST (1522699200)
> Apr  2 22:00:20 weewx weewx[13633]: forecast: ZambrettiThread: Zambretti: saved 1 forecast records
> Apr  2 22:00:20 weewx weewx[13633]: forecast: ZambrettiThread: Zambretti: deleted forecasts prior to 1522094420
> Apr  2 22:00:21 weewx weewx[13633]: cheetahgenerator: Generated 7 files for report StandardReport in 0.49 seconds
> Apr  2 22:00:21 weewx weewx[13633]: restx: Wunderground-PWS: Published record 2018-04-02 22:00:00 CEST (1522699200)
> Apr  2 22:00:21 weewx weewx[13633]: imagegenerator: Generated 24 images for StandardReport in 0.55 seconds
> Apr  2 22:00:21 weewx weewx[13633]: copygenerator: copied 5 files to /var/www/html/weewx
> Apr  2 22:00:22 weewx weewx[13633]: cheetahgenerator: Generated 1 files for report forecast in 0.25 seconds
> Apr  2 22:00:22 weewx weewx[13633]: copygenerator: copied 83 files to /var/www/html/weewx/forecast
> Apr  2 22:00:22 weewx weewx[13633]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
> Apr  2 22:00:22 weewx weewx[13633]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Data/data.txt.tmpl
> Apr  2 22:00:22 weewx weewx[13633]: cheetahgenerator: **** Reason: cannot find 'moon' while searching for 'almanac.moon.rise'
> Apr  2 22:00:22 weewx weewx[13633]: ****  Traceback (most recent call last):
> Apr  2 22:00:22 weewx weewx[13633]: ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 330, in generate
> Apr  2 22:00:22 weewx weewx[13633]: ****      print >> _file, compiled_template
> Apr  2 22:00:22 weewx weewx[13633]: ****    File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1005, in __str__
> Apr  2 22:00:22 weewx weewx[13633]: ****      rc = getattr(self, mainMethName)()
> Apr  2 22:00:22 weewx weewx[13633]: ****    File "_etc_weewx_skins_Data_data_txt_tmpl.py", line 231, in respond
> Apr  2 22:00:22 weewx weewx[13633]: ****  NotFound: cannot find 'moon' while searching for 'almanac.moon.rise'
> Apr  2 22:00:22 weewx weewx[13633]: cheetahgenerator: Generated 0 files for report Data in 0.05 seconds
> Apr  2 22:05:23 weewx weewx[13633]: manager: Added record 2018-04-02 22:05:00 CEST (1522699500) to database 'weewx.sdb'
> Apr  2 22:05:23 weewx weewx[13633]: manager: Added record 2018-04-02 22:05:00 CEST (1522699500) to daily summary in 'weewx.sdb'
> Apr  2 22:05:23 weewx weewx[13633]: restx: MQTT: Published record 2018-04-02 22:05:00 CEST (1522699500)
> Apr  2 22:05:23 weewx weewx[13633]: cheetahgenerator: Generated 7 files for report StandardReport in 0.20 seconds
> Apr  2 22:05:24 weewx weewx[13633]: imagegenerator: Generated 12 images for StandardReport in 0.20 seconds
> Apr  2 22:05:24 weewx weewx[13633]: copygenerator: copied 0 files to /var/www/html/weewx
> Apr  2 22:05:24 weewx weewx[13633]: cheetahgenerator: Generated 1 files for report forecast in 0.14 seconds
> Apr  2 22:05:24 weewx weewx[13633]: copygenerator: copied 0 files to /var/www/html/weewx/forecast
> Apr  2 22:05:24 weewx weewx[13633]: cheetahgenerator: Generate failed with exception '<class 'NameMapper.NotFound'>'
> Apr  2 22:05:24 weewx weewx[13633]: cheetahgenerator: **** Ignoring template /etc/weewx/skins/Data/data.txt.tmpl
> 
```

******  NotFound: cannot find 'moon' while searching for 'almanac.moon.rise' -->  Ignoring template /etc/weewx/skins/Data/data.txt.tmpl**

There is nothing special in my weewx 3.8.0 installation. Added your addon as described in the wiki.
Do you need some more Infos to debug ? 

Weewx 3.8.0
Debian Stretch 9.0

Thanks for your help!

**Comment by evilbunny2008** [comment]
You may need to install pyephem

sudo pip install pyephem

I'll update my template to check before using, thanks for bringing this to my attention.

**Comment by BeNeDeLuX** [comment]
pyephem is installed. Here is my current output:
```

root@weewx:~# pip list --format columns
Package        Version
-------------- -----------
beautifulsoup4 4.5.3
chardet        2.3.0
Cheetah        2.4.4
configobj      5.0.6
html5lib       0.999999999
lxml           3.7.1
paho-mqtt      1.3.1
Pillow         4.0.0
pip            9.0.3
pyephem        3.7.6.0
pylibpcap      0.6.4
pyserial       3.2.1
pyusb          1.0.0
setuptools     33.1.1
six            1.10.0
webencodings   0.5
```

**Comment by evilbunny2008** [comment]
Do you still have the default skin with the moon info? Below is mine...

```
# pip list --format columns
Package         Version
--------------- -------
Cheetah         2.4.4  
configobj       5.0.6  
mysqlclient     1.3.7  
Pillow          4.0.0  
pip             9.0.1  
pyephem         3.7.6.0
pyserial        3.2.1  
python-dateutil 2.6.1  
pyusb           1.0.0  
setuptools      33.1.1 
six             1.10.0 
speedtest-cli   1.0.0  
virtualenv      15.1.0 
wheel           0.30.0 
```

**Comment by BeNeDeLuX** [comment]
> Do you still have the default skin with the moon info?

Ok, there is the problem. No i´m not using the default skin. I use "blauesledersofa" from here --> https://www.patsblog.de/2015/09/26/weewx-skin-flat-template-von-blauesledersofa-in-deutsch/

Do you know which part/files i need to add from the default skin ?

**Comment by evilbunny2008** [comment]
It should work without the default skin, I only mentioned it because the main page shows moon information.

**Comment by evilbunny2008** [comment]
just a quick check, does the almanac.moon.rise in data.txt.tmpl have a $ in front of it?

**Comment by BeNeDeLuX** [comment]
Yes there is a $ in front of it:
```
root@weewx:/etc/weewx/skins/Data# cat data.txt.tmpl | grep almac*
$almanac.moon.rise|$almanac.moon.set|$almanac.next_full_moon|$almanac.next_new_moon|$almanac.moon_phase|$almanac.moon_fullness|#slurp
$day.ET.sum.formatted|$current.dateTime.format("%a, %d %b %Y")|$current.dateTime.format("%H:%M %Z")|$station.location|$almanac.sun.rise|$almanac.sun.set|$almanac.sun.transit|#slurp
root@weewx:/etc/weewx/skins/Data#
```
**BUT: It is working now!** After install pyephem and reboot the complete Server instead of only the weewx service the data.txt is generated!

Cool! Thanks for your quick help. Will go on with the App.
