### ISSUE TITLE
Create own directory

### ISSUE THREAD

**Issue by MartinBrucker** [evilbunny2008/weeWxWeatherApp#8]
Hey,
i encountered following problem:

I downloaded the extension explained like in the wiki for the metric version. 

`mbrucker@raspberrypi:~ $ wee_extension --install inigo-metric.tar.gz

Request to install 'inigo-metric.tar.gz'
Extracting from tar archive inigo-metric.tar.gz
Traceback (most recent call last):
  File "/usr/bin/wee_extension", line 82, in <module>
    main()
  File "/usr/bin/wee_extension", line 74, in main
    ext.install_extension(options.install)
  File "/usr/share/weewx/weecfg/extension.py", line 116, in install_extension
    self.install_from_dir(extension_dir)
  File "/usr/share/weewx/weecfg/extension.py", line 174, in install_from_dir
    shutil.copy(source_path, destination_path)
  File "/usr/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/etc/weewx/skins/Inigo/inigo-data.txt.tmpl'
`
I tried it without and with sudo, it failed twice.

After creating the directory /etc/weewx/Inigo, via `sudo mkdir /etc/weewx/Inigo` everything worked well. Is it somehow possible to let the extension create its own folder? 

Its just a minor thing but still it might stop people using this extension since they cant get glue out of the error msg.

-Martin

**Comment by evilbunny2008** [comment]
What happens if you do the following?

` sudo wee_extension --verbosity=3 --install inigo-metric.tar.gz`
